### ISSUE TITLE
bug: Boolean functions not recognized

### ISSUE THREAD

**Issue by smoeding** [tree-sitter-grammars/tree-sitter-puppet#10]
### Did you check existing issues?

- [ ] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

The parser does not recogize boolean functions as conditions. If a function returns a boolean value it should be sufficient to call the function without comparing the result to anything.

### Steps To Reproduce/Bad Parse Tree

The following code is a valid puppet statement:
```puppet
if empty("") {
  notice("foo")
}
```

The function call does not seem to be parsed correctly:
```
(source_file
 (ERROR if
  (function_call (identifier) (
   (string " ")
   )
   (lambda
    (block {
     (function_call (identifier) (
      (string " (string_content) ")
      ))
     })))))
```

### Expected Behavior/Parse Tree

Unary expressions using a function should be possible as conditions for if/elsif/until/...

**Comment by amaanq** [comment]
fixed on master
