### ISSUE TITLE
bug: Only last element of resource or class with a namespace is highlighted

### ISSUE THREAD

**Issue by nvergottini** [tree-sitter-grammars/tree-sitter-puppet#13]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

With resource or class names with a namespace, only the last element of the name is highlighted.

![image](https://github.com/tree-sitter-grammars/tree-sitter-puppet/assets/28265335/0b619d6f-951d-4d9c-9d90-9240d4264dcb)

### Steps To Reproduce/Bad Parse Tree

TSInspectTree shows a class identifier as containing more than one identifier, but only the last identifier within the class identifier is highlighted.

```
(comment) ; [1:1 - 23]
(class_definition) ; [2:1 - 8:1]
 (class_identifier) ; [2:7 - 19]
  (identifier) ; [2:7 - 13]
  (identifier) ; [2:16 - 19]
 (block) ; [2:21 - 8:1]
  (include_statement) ; [3:3 - 31]
   (class_identifier) ; [3:11 - 31]
    (identifier) ; [3:11 - 17]
    (identifier) ; [3:20 - 23]
    (identifier) ; [3:26 - 31]
  (resource_declaration) ; [5:3 - 7:3]
   type: (class_identifier) ; [5:3 - 25]
    (identifier) ; [5:3 - 9]
    (identifier) ; [5:12 - 15]
    (identifier) ; [5:18 - 25]
   title: (string) ; [5:29 - 40]
    (string_content) ; [5:30 - 39]
   (attribute) ; [6:5 - 21]
    name: (identifier) ; [6:5 - 10]
    value: (identifier) ; [6:15 - 21]
```

### Expected Behavior/Parse Tree

All identifiers within a class or resource identifier (or just the entire class identifier including ::) should be highlighted the same.

### Repro

```puppet
class profile::test {
  include profile::test::common

  profile::test::resource { 'myresource':
    ensure => present,
  }

  package { 'test':
    ensure => installed,
  }
}
```

**Comment by amaanq** [comment]
belongs in nvim-treesitter (or whatever tool you use for highlighting), this is just the parser repo
